package gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author nevinkishore
 */
public class leaderboard extends javax.swing.JFrame {

    /**
     * Creates new form leaderboard
     */
    public leaderboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        startbutton = new javax.swing.JButton();
        LEADERBOARD = new javax.swing.JButton();
        EXITBTTN = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/leaderboardback.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startbutton.setText("START");
        startbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(startbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        LEADERBOARD.setText("LEADERBOARD");
        LEADERBOARD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LEADERBOARDActionPerformed(evt);
            }
        });
        getContentPane().add(LEADERBOARD, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        EXITBTTN.setText("EXIT");
        EXITBTTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITBTTNActionPerformed(evt);
            }
        });
        getContentPane().add(EXITBTTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbuttonActionPerformed
        new Menu().setVisible(true);
    dispose();  // Close the main menu
    }//GEN-LAST:event_startbuttonActionPerformed

    private void LEADERBOARDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LEADERBOARDActionPerformed
//        JOptionPane.showMessageDialog(this, "Leaderboard not implemented yet!");
    }//GEN-LAST:event_LEADERBOARDActionPerformed

    private void EXITBTTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITBTTNActionPerformed
       System.exit(0);
    }//GEN-LAST:event_EXITBTTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new leaderboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXITBTTN;
    private javax.swing.JButton LEADERBOARD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton startbutton;
    // End of variables declaration//GEN-END:variables
}
